
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Validate an HF token by calling /api/whoami-v2.
 * On success, stores the token in the OS keychain and updates in-memory state.
 */
async validateToken(token: string) : Promise<Result<UserInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Logout: clears in-memory auth state and removes token from OS keychain.
 */
async logout() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("logout") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the stored token from in-memory state or OS keychain.
 */
async getStoredToken() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_stored_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check for an existing HF token from keychain or filesystem.
 * Checks in order: OS keychain, ~/.cache/huggingface/token, ~/.huggingface/token (legacy).
 * Returns None if no token is found anywhere.
 */
async checkExistingToken() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_existing_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start an OAuth browser login flow using PKCE.
 * Returns the HF authorize URL to open in the browser.
 * A localhost server is started to receive the callback.
 */
async oauthStart() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("oauth_start") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Exchange an OAuth authorization code for an access token.
 * Validates CSRF state, exchanges code via PKCE, stores token in keyring.
 */
async oauthExchangeCode(callbackUrl: string) : Promise<Result<UserInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("oauth_exchange_code", { callbackUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel an in-progress OAuth flow, clearing stored PKCE state.
 */
async oauthCancel() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("oauth_cancel") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enqueue a file for upload. Validates the file exists, inserts a DB row,
 * and kicks the queue so a worker starts if capacity is available.
 */
async enqueueUpload(filePath: string, repoId: string, repoType: string, revision: string, commitMessage: string, priority: boolean) : Promise<Result<UploadJob, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enqueue_upload", { filePath, repoId, repoType, revision, commitMessage, priority }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel a specific upload by job ID.
 */
async cancelUpload(jobId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_upload", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pause a specific upload by job ID.
 */
async pauseUpload(jobId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_upload", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resume a paused upload by setting its state back to "pending" and kicking the queue.
 */
async resumeUpload(jobId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_upload", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pause all active uploads. Returns the number of uploads paused.
 */
async pauseAllUploads() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_all_uploads") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all upload jobs (all states) ordered by priority then creation time.
 */
async listUploads() : Promise<Result<UploadJob[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_uploads") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle priority on an upload job.
 */
async setUploadPriority(jobId: string, priority: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_upload_priority", { jobId, priority }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start the progress monitoring channel. The channel emits Vec<UploadProgress>
 * every 500ms containing all currently active upload jobs.
 * 
 * The frontend receives batched updates — never per-chunk.
 * Also drives tray icon animation and menu updates at the same cadence.
 */
async startUploadMonitoring(channel: TAURI_CHANNEL<UploadProgress[]>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_upload_monitoring", { channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update the concurrent upload limit (1-5). Persisted to tauri-plugin-store
 * so the value survives app restarts.
 */
async setConcurrentLimit(limit: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_concurrent_limit", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type UploadJob = { id: string; file_path: string; file_name: string; repo_id: string; repo_type: string; revision: string; commit_message: string; total_bytes: number; bytes_confirmed: number; protocol: UploadProtocol | null; state: UploadJobState; priority: boolean; retry_count: number; last_error: string | null; created_at: number; updated_at: number }
export type UploadJobState = "pending" | "hashing" | "uploading" | "committing" | "done" | "failed" | "paused" | "cancelled"
export type UploadProgress = { job_id: string; bytes_sent: number; total_bytes: number; speed_bps: number; eta_seconds: number; state: UploadJobState }
export type UploadProtocol = "xet" | "lfs_multipart"
export type UserInfo = { name: string; fullname: string | null; 
/**
 * HF API returns "avatarUrl" — rename to snake_case for consistency across Rust and TypeScript.
 */
avatar_url: string | null; email: string | null; 
/**
 * HF API returns "type" — rename to avoid Rust keyword conflict.
 * When serializing, use "type" (what HF API expects).
 * When deserializing, accept both "type" and "user_type".
 */
type: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
