// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

import { invoke as TAURI_INVOKE } from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
  mappings: T
): {
  [K in keyof T]: __EventObj__<T[K]>;
} {
  return new Proxy(
    {} as any,
    {
      get: (_, event) => ({
        listen: (arg: any) => TAURI_API_EVENT.listen(event as string, arg),
        once: (arg: any) => TAURI_API_EVENT.once(event as string, arg),
        emit: (arg: any) => TAURI_API_EVENT.emit(event as string, arg),
      }),
    }
  );
}

export type UserInfo = {
  name: string;
  fullname: string | null;
  avatar_url: string | null;
  email: string | null;
  type: string | null;
};

export const commands = {
  async validateToken(token: string): Promise<UserInfo> {
    return await TAURI_INVOKE<UserInfo>("validate_token", { token });
  },
  async logout(): Promise<void> {
    return await TAURI_INVOKE<void>("logout");
  },
  async getStoredToken(): Promise<string | null> {
    return await TAURI_INVOKE<string | null>("get_stored_token");
  },
  async checkExistingToken(): Promise<string | null> {
    return await TAURI_INVOKE<string | null>("check_existing_token");
  },
};

export const events = __makeEvents__<{}>({});
