
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Validate an HF token by calling /api/whoami-v2.
 * On success, stores the token in the OS keychain and updates in-memory state.
 */
async validateToken(token: string) : Promise<Result<UserInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Logout: clears in-memory auth state and removes token from OS keychain.
 */
async logout() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("logout") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the stored token from in-memory state or OS keychain.
 */
async getStoredToken() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_stored_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check for an existing HF token from keychain or filesystem.
 * Checks in order: OS keychain, ~/.cache/huggingface/token, ~/.huggingface/token (legacy).
 * Returns None if no token is found anywhere.
 */
async checkExistingToken() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_existing_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start an OAuth browser login flow using PKCE.
 * Returns the HF authorize URL to open in the browser.
 */
async oauthStart() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("oauth_start") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Exchange an OAuth authorization code for an access token.
 * Validates CSRF state, exchanges code via PKCE, stores token in keyring.
 */
async oauthExchangeCode(callbackUrl: string) : Promise<Result<UserInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("oauth_exchange_code", { callbackUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel an in-progress OAuth flow, clearing stored PKCE state.
 */
async oauthCancel() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("oauth_cancel") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type UploadJobState = "pending" | "hashing" | "uploading" | "committing" | "done" | "failed" | "paused" | "cancelled";
export type UploadProtocol = "xet" | "lfs_multipart";

// Re-export upload types from commands/upload.ts for convenience
export type { UploadJob, UploadProgress } from './commands/upload';

export type UserInfo = { name: string; fullname: string | null;
/**
 * HF API returns "avatarUrl" — rename to snake_case for consistency across Rust and TypeScript.
 */
avatar_url: string | null; email: string | null; 
/**
 * HF API returns "type" — rename to avoid Rust keyword conflict.
 * When serializing, use "type" (what HF API expects).
 * When deserializing, accept both "type" and "user_type".
 */
type: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
